# Generated by Django 3.0.8 on 2020-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='patient_gender',
            field=models.CharField(choices=[('женский', 'женский'), ('мужской', 'мужской')], default='женский', max_length=30),
        ),
    ]
