# Generated by Django 3.0.8 on 2020-07-22 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_form', '0002_form_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='date',
        ),
        migrations.AddField(
            model_name='form',
            name='form_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
