# Generated by Django 3.0.8 on 2020-07-24 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_form', '0003_auto_20200722_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='result',
            field=models.CharField(default='', max_length=30, verbose_name='Заключение'),
        ),
        migrations.AlterField(
            model_name='form',
            name='bloodflow_1',
            field=models.CharField(max_length=30, verbose_name='Кровоток 1'),
        ),
        migrations.AlterField(
            model_name='form',
            name='bloodflow_2',
            field=models.CharField(max_length=30, verbose_name='Кровоток 2'),
        ),
        migrations.AlterField(
            model_name='form',
            name='comment_1',
            field=models.CharField(max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='form',
            name='comment_2',
            field=models.CharField(max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='form',
            name='comment_3',
            field=models.CharField(max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='form',
            name='contours',
            field=models.CharField(max_length=30, verbose_name='Контуры'),
        ),
        migrations.AlterField(
            model_name='form',
            name='echogenicity',
            field=models.CharField(max_length=30, verbose_name='Эхогенность'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='form',
            name='histology',
            field=models.CharField(max_length=30, verbose_name='Гистология'),
        ),
        migrations.AlterField(
            model_name='form',
            name='microcalcinates',
            field=models.CharField(max_length=30, verbose_name='Микрокальцинаты'),
        ),
        migrations.AlterField(
            model_name='form',
            name='patient_age',
            field=models.CharField(max_length=30, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='form',
            name='patient_gender',
            field=models.CharField(choices=[('женский', 'женский'), ('мужской', 'мужской')], default='женский', max_length=30, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='form',
            name='patient_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='form',
            name='solidity',
            field=models.CharField(max_length=30, verbose_name='Солидность'),
        ),
        migrations.AlterField(
            model_name='form',
            name='verticalization',
            field=models.CharField(max_length=30, verbose_name='Вертикализация'),
        ),
    ]
